name: fish_and_meat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^9.2.2
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^3.1.0
  get: ^4.7.2
  http: ^1.3.0
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  multipart: ^0.1.2
  provider: ^6.1.4
  razorpay_flutter: ^1.4.0
  shared_preferences: ^2.5.2
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/HelveticaNeueBold.otf

  fonts:
    - family: helveticaBold
      fonts:
        - asset: assets/fonts/HelveticaNeueBold.otf
